### ISSUE TITLE
PointNext Runtime error

### ISSUE THREAD

**Issue by lightxu** [salesforce/ULIP#28]
Hi ULIP authors!

I am trying to run test on PointNext model using the given script, however it gives me this shape mismatch error, could you help take a look what might go wrong?

`RuntimeError: Given groups=1, weight of size [32, 4, 1], expected input[64, 3, 8192] to have 4 channels, but got 3 channels instead`

Full log:

```
$ bash ./scripts/test_pointnext.sh ./data/pretrained_models/ckpt_zero-sho_classification/checkpoint_pointnext.pt
2023-04-29 08:48:13,941 - ModelNet - INFO - The size of test data is 2468
2023-04-29 08:48:13,944 - ModelNet - INFO - Load processed data from data/modelnet40_normal_resampled/modelnet40_test_8192pts_fps.dat...
Not using distributed mode
=> creating model: ULIP_PN_NEXT
model size:
1363264
=> loaded resume checkpoint './data/pretrained_models/ckpt_zero-sho_classification/checkpoint_pointnext.pt'
=> encoding captions
Traceback (most recent call last):
  File "/mnt/d/cs231n_project/ULIP/main.py", line 545, in <module>
    main(args)
  File "/mnt/d/cs231n_project/ULIP/main.py", line 104, in main
    zero_stats = test_zeroshot_3d(args)
  File "/mnt/d/cs231n_project/ULIP/main.py", line 463, in test_zeroshot_3d
    results = test_zeroshot_3d_core(test_loader, model, tokenizer, args)
  File "/mnt/d/cs231n_project/ULIP/main.py", line 392, in test_zeroshot_3d_core
    pc_features = utils.get_model(model).encode_pc(pc)
  File "/mnt/d/cs231n_project/ULIP/models/ULIP_models.py", line 147, in encode_pc
    pc_feat = self.point_encoder(pc)
  File "/home/light/anaconda3/envs/ulip/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/d/cs231n_project/ULIP/./models/pointnext/PointNeXt/openpoints/models/classification/cls_base.py", line 31, in forward
    global_feat = self.encoder.forward_cls_feat(data)
  File "/mnt/d/cs231n_project/ULIP/./models/pointnext/PointNeXt/openpoints/models/backbone/pointnext.py", line 442, in forward_cls_feat
    p0, f0 = self.encoder[i]([p0, f0])
  File "/home/light/anaconda3/envs/ulip/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/light/anaconda3/envs/ulip/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/light/anaconda3/envs/ulip/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/d/cs231n_project/ULIP/./models/pointnext/PointNeXt/openpoints/models/backbone/pointnext.py", line 143, in forward
    f = self.convs(f)  # (n, c)
  File "/home/light/anaconda3/envs/ulip/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/light/anaconda3/envs/ulip/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/light/anaconda3/envs/ulip/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/light/anaconda3/envs/ulip/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/light/anaconda3/envs/ulip/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/light/anaconda3/envs/ulip/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/light/anaconda3/envs/ulip/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [32, 4, 1], expected input[64, 3, 8192] to have 4 channels, but got 3 channels instead```

**Comment by Tycho-Xue** [comment]
Hi @lightxu, sorry for the delay, thank for catching it! I think this error is due to the missing of --use_height, it seems I added it in the pre-train script but forgot that in the test script, I will update it soon.
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node=8 main.py --model ULIP_PN_NEXT --npoints 8192 --output-dir ./outputs/reproduce_pointnext_8kpts --lr 1e-3 --use_height

**Comment by labixiaochao** [comment]
> 谢谢 @Tycho-Xue ！添加标志后，我可以确认测试脚本是否正常工作。
> 
> 中更新了我的更改 [我已经在 #27 ](https://github.com/salesforce/ULIP/pull/27)。

invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number，mistake on top1_accurate = correct[:1].squeeze()
            top5_accurate = correct[:5].float().sum(0, keepdim=True).squeeze()
            for idx, name in enumerate(target_name):
                if top1_accurate[idx].item():
                    per_class_correct_top1[name] += 1
                if top5_accurate[idx].item():
                    per_class_correct_top5[name] += 1
