### ISSUE TITLE
pointnet2_ops install problem

### ISSUE THREAD

**Issue by Chopper-233** [salesforce/ULIP#42]
os:python3.8 cuda 11.3 pytorch 1.10.1
your code need the kernet pointnet2,so
while i'm running  the command  pip install "git+https://github.com/erikwijmans/Pointnet2_PyTorch.git#egg=pointnet2_ops&subdirectory=pointnet2_ops_lib", i meet the issue following,and i try many solutions found on the internet but no one worked,i hope you can help me solve it       nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "D:\Anaconda\envs\ulip\lib\site-packages\torch\utils\cpp_extension.py", line 1723, in _run_ninja_build
          env=env)
        File "D:\Anaconda\envs\ulip\lib\subprocess.py", line 512, in run
          output=stdout, stderr=stderr)
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\李文峤\AppData\Local\Temp\pip-install-kwvdlqzz\pointnet2-ops_fc850762ca7249e1bbcb92749807b38c\pointnet2_ops_lib\setup.py", line 38, in <module>
          include_package_data=True,
        File "D:\Anaconda\envs\ulip\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "D:\Anaconda\envs\ulip\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "D:\Anaconda\envs\ulip\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "D:\Anaconda\envs\ulip\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "D:\Anaconda\envs\ulip\lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "D:\Anaconda\envs\ulip\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\Anaconda\envs\ulip\lib\site-packages\setuptools\command\install.py", line 68, in run
          return orig.install.run(self)
        File "D:\Anaconda\envs\ulip\lib\site-packages\setuptools\_distutils\command\install.py", line 698, in run
          self.run_command('build')
        File "D:\Anaconda\envs\ulip\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "D:\Anaconda\envs\ulip\lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "D:\Anaconda\envs\ulip\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\Anaconda\envs\ulip\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "D:\Anaconda\envs\ulip\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "D:\Anaconda\envs\ulip\lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "D:\Anaconda\envs\ulip\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\Anaconda\envs\ulip\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "D:\Anaconda\envs\ulip\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
          self.build_extensions()
        File "D:\Anaconda\envs\ulip\lib\site-packages\torch\utils\cpp_extension.py", line 735, in build_extensions
          build_ext.build_extensions(self)
        File "D:\Anaconda\envs\ulip\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 468, in build_extensions
          self._build_extensions_serial()
        File "D:\Anaconda\envs\ulip\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 494, in _build_extensions_serial
          self.build_extension(ext)
        File "D:\Anaconda\envs\ulip\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "D:\Anaconda\envs\ulip\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 556, in build_extension
          depends=ext.depends,
        File "D:\Anaconda\envs\ulip\lib\site-packages\torch\utils\cpp_extension.py", line 717, in win_wrap_ninja_compile
          with_cuda=with_cuda)
        File "D:\Anaconda\envs\ulip\lib\site-packages\torch\utils\cpp_extension.py", line 1404, in _write_ninja_file_and_compile_objects
          error_prefix='Error compiling objects for extension')
        File "D:\Anaconda\envs\ulip\lib\site-packages\torch\utils\cpp_extension.py", line 1733, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pointnet2_ops

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by iLori-Jiang** [comment]
I meet the same problem. Have you solved it?
