### ISSUE TITLE
No module named 'pointnet2_ops'

### ISSUE THREAD

**Issue by eric-stumpe** [salesforce/ULIP#67]
Hello,

I followed all steps of the installation instructions, but when executing a test case, I got the following error (Windows10):

D:\Work\ULIP-main>python main.py --model ULIP2_PointBERT_Colored --npoints 10000 --output-dir ./outputs/test_pointbert_8kpts --evaluate_3d_ulip2 --validate_dataset_name=modelnet40 --test_ckpt_addr ./data/pretrained_models/ckpt_zero-sho-classification/pointbert_ULIP-2.pt
Not using distributed mode
=> creating model: ULIP2_PointBERT_Colored
Get openclip model:
Finished loading the openclip model.
Traceback (most recent call last):
  File "main.py", line 576, in <module>
    main(args)
  File "main.py", line 109, in main
    zero_stats = test_zeroshot_3d_ulip2(args)
  File "main.py", line 482, in test_zeroshot_3d_ulip2
    model = getattr(models, args.model)(args=args)
  File "D:\Work\ULIP-main\models\ULIP_models.py", line 361, in ULIP2_PointBERT_Colored
    from models.pointbert.point_encoder import PointTransformer, PointTransformer_Colored
  File "D:\Work\ULIP-main\models\pointbert\point_encoder.py", line 5, in <module>
    from models.pointbert.dvae import Group
  File "D:\Work\ULIP-main\models\pointbert\dvae.py", line 4, in <module>
    from models.pointbert import misc
  File "D:\Work\ULIP-main\models\pointbert\misc.py", line 10, in <module>
    from pointnet2_ops import pointnet2_utils
ModuleNotFoundError: No module named 'pointnet2_ops

To provide some better insight for reproducability, these are the exact steps I undertook:

1. created the conda environment and activated it
2. conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=11.3 -c pytorch -c conda-forge
3. pip install -r requirements.txt
4. downloaded both modelnet40_normal_resampled and initialize_models folders
5. downloaded the PointBERT_ULIP-2(xyz input) pretrained model and copied it into: 
ULIP-main\data\pretrained_models\ckpt_zero-sho-classification
6. executed in anaconda prompt: (lip) D:\Work\ULIP-main>python main.py --model ULIP2_PointBERT_Colored --npoints 10000 --output-dir ./outputs/test_pointbert_8kpts --evaluate_3d_ulip2 --validate_dataset_name=modelnet40 --test_ckpt_addr ./data/pretrained_models/ckpt_zero-sho-classification/pointbert_ULIP-2.pt

At this point I got one more error, stating that matplotlib was missing, which I fixed with pip install matplotlib.

What do you suggest to overcome this issue?

Kind Regards

**Comment by labixiaochao** [comment]
> Hello,
> 
> I followed all steps of the installation instructions, but when executing a test case, I got the following error (Windows10):
> 
> D:\Work\ULIP-main>python main.py --model ULIP2_PointBERT_Colored --npoints 10000 --output-dir ./outputs/test_pointbert_8kpts --evaluate_3d_ulip2 --validate_dataset_name=modelnet40 --test_ckpt_addr ./data/pretrained_models/ckpt_zero-sho-classification/pointbert_ULIP-2.pt Not using distributed mode => creating model: ULIP2_PointBERT_Colored Get openclip model: Finished loading the openclip model. Traceback (most recent call last): File "main.py", line 576, in main(args) File "main.py", line 109, in main zero_stats = test_zeroshot_3d_ulip2(args) File "main.py", line 482, in test_zeroshot_3d_ulip2 model = getattr(models, args.model)(args=args) File "D:\Work\ULIP-main\models\ULIP_models.py", line 361, in ULIP2_PointBERT_Colored from models.pointbert.point_encoder import PointTransformer, PointTransformer_Colored File "D:\Work\ULIP-main\models\pointbert\point_encoder.py", line 5, in from models.pointbert.dvae import Group File "D:\Work\ULIP-main\models\pointbert\dvae.py", line 4, in from models.pointbert import misc File "D:\Work\ULIP-main\models\pointbert\misc.py", line 10, in from pointnet2_ops import pointnet2_utils ModuleNotFoundError: No module named 'pointnet2_ops
> 
> To provide some better insight for reproducability, these are the exact steps I undertook:
> 
>     1. created the conda environment and activated it
> 
>     2. conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=11.3 -c pytorch -c conda-forge
> 
>     3. pip install -r requirements.txt
> 
>     4. downloaded both modelnet40_normal_resampled and initialize_models folders
> 
>     5. downloaded the PointBERT_ULIP-2(xyz input) pretrained model and copied it into:
>        ULIP-main\data\pretrained_models\ckpt_zero-sho-classification
> 
>     6. executed in anaconda prompt: (lip) D:\Work\ULIP-main>python main.py --model ULIP2_PointBERT_Colored --npoints 10000 --output-dir ./outputs/test_pointbert_8kpts --evaluate_3d_ulip2 --validate_dataset_name=modelnet40 --test_ckpt_addr ./data/pretrained_models/ckpt_zero-sho-classification/pointbert_ULIP-2.pt
> 
> 
> At this point I got one more error, stating that matplotlib was missing, which I fixed with pip install matplotlib.
> 
> What do you suggest to overcome this issue?
> 
> Kind Regards

May I ask if your issue has been resolved? I have also encountered the same problem

**Comment by SanBingYouYong** [comment]
It seems to be a typo in the import. Change the line to `from ..pointnet2 import pointnet2_utils` will fix it.
